[package]
name = "ap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli
clap = "2.33.3"

# file system
dirs = "3.0.2"
glob = "0.3.0"

# log
log = "0.4.14"
pretty_env_logger = "0.4.0"

# config
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"

# ui
termion = "1.5.6"
is_executable = "1.0.1"
term-kit =  { path = "../term-kit" }

[dev-dependencies]
pretty_assertions = "0.7.2"
